version: '3.9'

services:
  frontend:
    image: ghcr.io/otternode-io/frontend
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    ports:
      - target: 3000
        published: 3000

