version: '3.9'

services:
  smart-contract-verifier:
    image: ghcr.io/otternode-io/smart-contract-verifier
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ../envs/common-smart-contract-verifier.env
